server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location /hls/ {
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Headers "Authorization,Range,Content-Type" always;
    add_header Access-Control-Expose-Headers "Content-Length,Content-Range" always;
    try_files $uri =404;
  }

  location /keys/ {
    return 404;
  }
}
